version: '2'
services:
    reservationsystem-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/reservationsystem/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=reservationsystem
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
